[package]
name = "cli"
version = "0.5.5"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
tracing-subscriber = "0.3.18"
lazy_static = "1.4.0"
rookie = { path = "../rookie-rs", version = "0.5.5" }
serde_json = "1.0.107"
