name: Publish Crate

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Prepare appbound binaries (Used on Windows only.)
        run: |
          wget https://github.com/thewh1teagle/rookie/releases/download/appbound-binaries/paexec.exe -O rookie-rs/src/paexec.rs
          wget https://github.com/thewh1teagle/rookie/releases/download/appbound-binaries/unprotect.exe -O rookie-rs/src/unprotect.rs
      - run: cargo publish -p rookie --features appbound
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
